#!/usr/bin/env bash
# Generate docs/catalog.md from all SKILL.md/agent frontmatter.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${REPO_DIR}/docs/catalog.md"
TODAY=$(date +%Y-%m-%d)

# Parse a frontmatter field from a file
get_field() {
  local file="$1"
  local field="$2"
  awk '/^---$/{c++; next} c==1{print}' "$file" \
    | grep -E "^${field}:" \
    | head -1 \
    | sed -E "s/^${field}:[[:space:]]*//" \
    | tr -d '"' | tr -d "'" \
    | sed 's/|//g' \
    | xargs
}

{
  echo "<!-- AUTO-GENERATED by scripts/build-catalog.sh on ${TODAY}. DO NOT EDIT. -->"
  echo
  echo "# Catalog"
  echo
  echo "_Last generated: ${TODAY}_"
  echo

  # ---------- Skills ----------
  echo "## Skills"
  echo
  echo "| Team | Slug | Status | Version | Owner | Description |"
  echo "|---|---|---|---|---|---|"
  while IFS= read -r -d '' skill_md; do
    dir=$(dirname "$skill_md")
    team=$(basename "$(dirname "$dir")")
    slug=$(basename "$dir")
    status=$(get_field "$skill_md" status)
    version=$(get_field "$skill_md" version)
    owner=$(get_field "$skill_md" owner)
    desc=$(get_field "$skill_md" description)
    echo "| ${team} | [\`${slug}\`](../skills/${team}/${slug}/) | ${status:-?} | ${version:-?} | ${owner:-?} | ${desc:-} |"
  done < <(find "${REPO_DIR}/skills" -mindepth 3 -maxdepth 3 -name "SKILL.md" -print0 2>/dev/null | sort -z)
  echo

  # ---------- Agents ----------
  echo "## Agents"
  echo
  echo "| Team | Slug | Status | Owner | Description |"
  echo "|---|---|---|---|---|"
  while IFS= read -r -d '' agent_md; do
    team=$(basename "$(dirname "$agent_md")")
    slug=$(basename "$agent_md" .md)
    status=$(get_field "$agent_md" status)
    owner=$(get_field "$agent_md" owner)
    desc=$(get_field "$agent_md" description)
    echo "| ${team} | [\`${slug}\`](../agents/${team}/${slug}.md) | ${status:-?} | ${owner:-?} | ${desc:-} |"
  done < <(find "${REPO_DIR}/agents" -mindepth 2 -maxdepth 2 -name "*.md" -print0 2>/dev/null | sort -z)
  echo

  # ---------- Commands ----------
  echo "## Commands"
  echo
  echo "| Slug | Owner | Description |"
  echo "|---|---|---|"
  while IFS= read -r -d '' cmd_md; do
    slug=$(basename "$cmd_md" .md)
    owner=$(get_field "$cmd_md" owner)
    desc=$(get_field "$cmd_md" description)
    echo "| \`/${slug}\` | ${owner:-?} | ${desc:-} |"
  done < <(find "${REPO_DIR}/commands" -mindepth 1 -maxdepth 1 -name "*.md" -print0 2>/dev/null | sort -z)
} > "$OUT"

echo "✓ Catalog written to ${OUT}"
